### ISSUE TITLE
Internasional Cost

### ISSUE THREAD

**Issue by rezadaulay** [hrsetyono/woocommerce-ongkir#45]
apakah mendukung internasional cost rajaongkir?

**Comment by hrsetyono** [comment]
Belum bisa gan, seharusnya diedit sedikit bisa sih tapi sekarang belum sempat.

Kalau agan bisa coding, mungkin bisa bantu ditambahkan, nanti saya merge.

Trims

**Comment by rezadaulay** [comment]
boleh gan, blh kasih clue mana aja yang perlu di edit

**Comment by hrsetyono** [comment]
Waduh agak lupa. Yang pasti `init-main.php` untuk setting page dan `init-zones.php` untuk proses kalkulasi.

Ada conditional IF yang aku taruh supaya kalkulasi nya jalan kalau country nya Indonesia. Itu perlu dihilangkan.

Di folder `/data` ada **couriers.json** untuk list Courier nya. Perlu ditambahkan yg internasional, mungkin Fedex dan sekawannya. Menambahkan disitu, entar otomatis di Setting page nya ada field baru.

Di `/admin/wcis-api.php` juga perlu ditambahkan untuk proses API internasional.
