### ISSUE TITLE
Issue dengan Extensions WooCommerce - Shipping Multiple Addresses

### ISSUE THREAD

**Issue by vishnupanji** [hrsetyono/woocommerce-ongkir#62]
Sebelumnya terima kasih telah membuat plugin yang sangat berguna ini mas.
Namun saya ada kendala ketika menggunakan Extension Shipping Multipe Addresses dari WooCommerce.

Ketika menambahkan alamat baru, field yg muncul hanya provinsi saja. Sehingga gagal mendapatkan informasi shipping cost nya.

**Comment by hrsetyono** [comment]
Halo @vishnupanji , saya tidak familiar dengan plugin itu. Sepertinya cukup rumit untuk di implementasikan.

Anda bisa membantu dengan fork repo ini dan coba menambahkan fitur agar bisa integrasi dengan plugin itu.
